spring.application.name=todo
# Altera o caminho para acessar a interface do Swagger (Padrão é /swagger-ui/index.html)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=admin
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# O Hibernate cria as tabelas automaticamente no Postgres ao subir
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true